# public/admin/config.yml

backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded med

# Here we define content structure
collections:
  - label: "Translations"
    name: "translations"
    folder: "src/translations"
    create: true