# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: hcastilhoeneida/translations_weblate
  branch: main
  identity_url: https://auth.decapbridge.com/sites/41c1fd8f-a497-4f53-a9bc-75f164f006ec
  gateway_url: https://gateway.decapbridge.com

i18n:
  structure: multiple_files
  locales: [en, de, en_AU, en_NZ]
  default_locale: en


media_folder: "public/images"
public_folder: "/images"

collections:
  - label: "Translations"
    name: "translations"
    folder: "translations"
    i18n:
      structure: multiple_files
      locales: [en, de, en_AU, en_NZ]
    create: true
    fields:
      - label: "Title"
        name: "fileTitle"
        widget: "string"
        i18n: true